### ISSUE TITLE
白色图片 一片空白

### ISSUE THREAD

**Issue by dj025** [JiuRanYa/iconSet#4]
白色图标 完全不显示 
![image](https://github.com/user-attachments/assets/27ac083c-be91-47d4-93b8-095f7a1bf97a)

**Comment by JiuRanYa** [comment]
@dj025 请问是什么系统，尝试清除重新上传也是空白吗

**Comment by dj025** [comment]
> @dj025 请问是什么系统，尝试清除重新上传也是空白吗

不是空白 是图标是白色的 白色图 界面也是白色

**Comment by JiuRanYa** [comment]
尝试清除重新上传也是空白图吗，请问您是什么系统

**Comment by dj025** [comment]
![image](https://github.com/user-attachments/assets/f7cea04a-c07f-46fb-aa1b-d9790fb7b041)
win11 就是白色的 

> 尝试清除重新上传也是空白图吗，请问您是什么系统

**Comment by JiuRanYa** [comment]
方便截图一下上传的图片文件夹吗，可以尝试清除后，重新上传试试，图标是存在浏览器本地的

**Comment by dj025** [comment]
![image](https://github.com/user-attachments/assets/f9935717-012f-4511-ab14-186ec062b814)
白色的图标

> 方便截图一下上传的图片文件夹吗，可以尝试清除后，重新上传试试，图标是存在浏览器本地的

**Comment by JiuRanYa** [comment]
@dj025 应该是白色的线条图在白色背景下重叠了，稍后我会支持一下暗色模式～

**Comment by dj025** [comment]
> @dj025 应该是白色的线条图在白色背景下重叠了，稍后我会支持一下暗色模式～

嗯 你到现在才知道我说的问题 不是不显示 是白色图 白色背景 重叠

**Comment by JiuRanYa** [comment]
@dj025 Hi，我已经发布了一个新的[Release](https://github.com/JiuRanYa/IconEase/releases/tag/v1.2.0)，支持暗色模式，该条issue暂时会被关闭~
